### ISSUE TITLE
我是菜鸟，看不懂怎么安装

### ISSUE THREAD

**Issue by wblbird** [hubeiwei/hello-yii2#6]
安装yii是会的，都是先安装好yii再安装其他扩展，你这个我看的不是懂

**Comment by hubeiwei** [comment]
我更新了一下说明，请指出是哪一步不会，我觉得执行那几句命令是没有问题的，如果是网站搭建这里不会的话，直接照抄我给出的就好了。

**Comment by wblbird** [comment]
比如yii2的安装有这个
php composer.phar create-project yiisoft/yii2-app-advanced advanced 2.0.11
你这个是不是也该有?
我比较菜未能理解。
是不是该有这个：
php composer.phar create-project hubeiwei/hello-yii2 
还是你这个要先装yII2，你这个再以扩展的方式安装？

**Comment by hubeiwei** [comment]
不需要，直接下载或 clone 代码下来按说明执行命令即可

**Comment by wblbird** [comment]
理解了，谢谢
